<?php

use yii\db\Schema;
use yii\db\Migration;

class m000000_000001_geo extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $cities  = __DIR__.'/data/city.tsv';
        $regions = __DIR__.'/data/region.tsv';

        $cities  = str_replace("\\", "/", $cities);
        $regions = str_replace("\\", "/", $regions);

        $this->createTable('geo_country', [
            'id'                        => $this->primaryKey(),
            'continent'                 => $this->string(2),
            'name_ru'                   => $this->string(128)->notNull(),
            'lat'                       => $this->decimal(6,2)->notNull(),
            'lon'                       => $this->decimal(6,2)->notNull(),
            'timezone'                  => $this->string(30)->notNull(),
            'iso2'                      => $this->string(2),                       // код страны 2 символа
            'short_name'                => $this->string(80)->notNull(),           // короткое название страны
            'long_name'                 => $this->string(80)->notNull(),           // длинное название страны
            'iso3'                      => $this->string(3),                       // код страны 3 символа
            'numcode'                   => $this->string(6),                       // цифровой код страны
            'un_member'                 => $this->string(12),
            'calling_code'              => $this->string(8),                       // телефонный код страны
            'cctld'                     => $this->string(5),                       // домен страны
            'phone_number_digits_code'  => $this->smallInteger(5),                 // количество цифр после кода
            'currency'                  => $this->string(3),                       // валюта страны
            'system_measure'            => $this->boolean()->defaultValue(false),  // система мер (0 - метрическая, 1 - английская)
        ], $tableOptions);

        $this->createTable('geo_region', [
            'id'         => Schema::TYPE_PK,
            'iso'        => 'VARCHAR(7) NOT NULL',
            'country'    => 'CHAR(2) NOT NULL',
            'name_ru'    => 'VARCHAR(128) NOT NULL',
            'name_en'    => 'VARCHAR(128) NOT NULL',
            'timezone'   => 'VARCHAR(30) NOT NULL',
            'okato'      => 'CHAR(4) NOT NULL',
        ], $tableOptions);

        $this->createTable('geo_city', [
            'id'         => Schema::TYPE_PK,
            'region_id'  => 'INTEGER',
            'name_ru'    => 'VARCHAR(128) NOT NULL',
            'name_en'    => 'VARCHAR(128) NOT NULL',
            'lat'        => 'DECIMAL(6,2) NOT NULL',
            'lon'        => 'DECIMAL(6,2) NOT NULL',
            'okato'      => 'VARCHAR(20) NOT NULL',
        ], $tableOptions);

        //$this->db->createCommand('LOAD DATA LOCAL INFILE "path/to/file.csv" IGNORE INTO TABLE geo_city;')->execute();
        $this->db->createCommand('LOAD DATA LOCAL INFILE "'.$cities.'" IGNORE INTO TABLE geo_city;')->execute();
        $this->db->createCommand('LOAD DATA LOCAL INFILE "'.$regions.'" IGNORE INTO TABLE geo_region;')->execute();

        $this->batchInsert('geo_country', ['id', 'continent', 'name_ru', 'lat', 'lon', 'timezone', 'iso2', 'short_name', 'long_name', 'iso3', 'numcode', 'un_member', 'calling_code', 'cctld', 'phone_number_digits_code',
            'currency', 'system_measure'],
            [
                [5, 'AS', 'Афганистан', 33.00, 66.00,	'Asia/Kabul', 'AF', Yii::t('app', 'Afghanistan'), 'Islamic Republic of Afghanistan', 'AFG', '004', 'yes', '93', '.af', null, 'AFA', 0],
                //[247, 'EU', 60.25, 20.00,'Europe/Mariehamn', 'AX', Yii::t('app', 'Aland Islands'), 'Aland Islands', 'ALA', '248', 'no', '358', '.ax', 10, null, 0],
                [8, 'EU', 'Албания', 41.00, 20.00,'Europe/Tirane', 'AL', Yii::t('app', 'Albania'), 'Republic of Albania', 'ALB', '008', 'yes', '355', '.al', 9, 'ALL', 0],
                [61, 'AF', 'Алжир', 28.00, 3.00, 'Africa/Algiers', 'DZ', Yii::t('app', 'Algeria'), 'People\'s Democratic Republic of Algeria', 'DZA', '012', 'yes', '213', '.dz', 9, 'DZD', 0],
                [14, 'OC', 'Американское Самоа', -14.23, -169.48, 'Pacific/Pago_Pago', 'AS', Yii::t('app', 'American Samoa'), 'American Samoa', 'ASM', '016', 'no', '1-684', '.as', 10, 'USD', 0],
                [3, 'EU', 'Андорра', 42.55, 1.58, 'Europe/Andorra', 'AD', Yii::t('app', 'Andorra'), 'Principality of Andorra', 'AND', '020', 'yes', '376', '.ad', null, 'EUR', 0],
                [11, 'AF', 'Ангола', -12.50, 18.50, 'Africa/Luanda', 'AO', Yii::t('app', 'Angola'), 'Republic of Angola', 'AGO', '024', 'yes', '244', '.ao', null, 'AOA', 0],
                [7, 'NA', 'Ангуилья', 18.22, -63.05, 'America/Anguilla', 'AI', Yii::t('app', 'Anguilla'), 'Anguilla', 'AIA', '660', 'no', '1-264', '.ai', 10, 'XCD', 0],
                [12, 'AN', 'Антарктида', -82.68, 8.79, 'NONE', 'AQ', Yii::t('app', 'Antarctica'), 'Antarctica', 'ATA', '010', 'no', '672', '.aq', null, 'NOK', 0],
                [6, 'NA', 'Антигуа и Барбуда', 17.05, -61.80, 'America/Antigua', 'AG', Yii::t('app', 'Antigua and Barbuda'), 'Antigua and Barbuda', 'ATG', '028', 'yes', '1-268', '.ag', 10, 'XCD', 0],
                [13, 'SA', 'Аргентина', -34.00, -64.00, 'America/Argentina/Buenos_Aires', 'AR', Yii::t('app', 'Argentina'), 'Argentine Republic', 'ARG', '032', 'yes', '54', '.ar', null, 'ARA', 0],
                [9, 'AS', 'Армения', 40.25, 45.00, 'Asia/Yerevan', 'AM', Yii::t('app', 'Armenia'), 'Republic of Armenia', 'ARM', '051', 'yes', '374', '.am', 8, 'AMD', 0],
                [17, 'NA', 'Арулько', 12.50, -69.97, 'America/Aruba', 'AW', Yii::t('app', 'Aruba'), 'Aruba', 'ABW', '533', 'no', '297', '.aw', null, 'AWG', 0],
                [16, 'OC', 'Австралия', -25.00, 135.00, 'Australia/Sydney', 'AU', Yii::t('app', 'Australia'), 'Commonwealth of Australia', 'AUS', '036', 'yes', '61', '.au', 9, 'AUD', 0],
                [15, 'EU', 'Австрия', 47.33, 13.33, 'Europe/Vienna', 'AT', Yii::t('app', 'Austria'), 'Republic of Austria', 'AUT', '040', 'yes', '43', '.at', 10, 'EUR', 0],
                [18, 'AS', 'Азербайджан', 40.50, 47.50, 'Asia/Baku', 'AZ', Yii::t('app', 'Azerbaijan'), 'Republic of Azerbaijan', 'AZE', '031', 'yes', '994', '.az', 9, 'AZM', 0],
                [32, 'NA', 'Багамские острова', 25.04, -77.37, 'America/Nassau', 'BS', Yii::t('app', 'Bahamas'), 'Commonwealth of The Bahamas', 'BHS', '044', 'yes', '1-242', '.bs', 10, 'BSD', 0],
                [25, 'AS', 'Бахрейн', 26.03, 50.55, 'Asia/Bahrain', 'BH', Yii::t('app', 'Bahrain'), 'Kingdom of Bahrain', 'BHR', '048', 'yes', '973', '.bh', 8, 'BHD', 0],
                [21, 'AS', 'Бангладеш', 24.00, 90.00, 'Asia/Dhaka', 'BD', Yii::t('app', 'Bangladesh'), 'People\'s Republic of Bangladesh', 'BGD', '050', 'yes', '880', '.bd', 10, 'BDT', 0],
                [20, 'NA', 'Барбадос', 13.17, -59.53, 'America/Barbados', 'BB', Yii::t('app', 'Barbados'), 'Barbados', 'BRB', '052', 'yes', '1-246', '.bb', 10, 'BBD', 0],
                [36, 'EU', 'Беларусь', 53.00, 28.00, 'Europe/Minsk', 'BY', Yii::t('app', 'Belarus'), 'Republic of Belarus', 'BLR', '112', 'yes', '375', '.by', 9, 'BYR', 0],
                [22, 'EU', 'Бельгия', 50.75, 4.50, 'Europe/Brussels', 'BE', Yii::t('app', 'Belgium'), 'Kingdom of Belgium', 'BEL', '056', 'yes', '32', '.be', 9, 'EUR', 0],
                [37, 'NA', 'Белиз', 17.25, -88.75, 'America/Belize', 'BZ', Yii::t('app', 'Belize'), 'Belize', 'BLZ', '084', 'yes', '501', '.bz', null, 'BZD', 0],
                [27, 'AF', 'Бенин', 9.50, 2.25, 'Africa/Porto-Novo', 'BJ', Yii::t('app', 'Benin'), 'Republic of Benin', 'BEN', '204', 'yes', '229', '.bj', null, 'XAF', 0],
                [28, 'NA', 'Бермуды', 32.33, -64.74, 'Atlantic/Bermuda', 'BM', Yii::t('app', 'Bermuda'), 'Bermuda Islands', 'BMU', '060', 'no', '1-441', '.bm', 10, 'BMD', 0],
                [33, 'AS', 'Бутан', 27.50, 90.50, 'Asia/Thimphu', 'BT', Yii::t('app', 'Bhutan'), 'Kingdom of Bhutan', 'BTN', '064', 'yes', '975', '.bt', null, 'BTN', 0],
                [30, 'SA', 'Боливия', -17.00, -65.00, 'America/La_Paz', 'BO', Yii::t('app', 'Bolivia'), 'Plurinational State of Bolivia', 'BOL', '068', 'yes', '591', '.bo', null, 'BOB', 0],
                //[253, 'NA', 12.21, -68.29, 'America/Kralendijk', 'BQ', Yii::t('app', 'Bonaire, Sint Eustatius and Saba'), 'Bonaire, Sint Eustatius and Saba', 'BES', '535', 'no', '599', '.bq', null, null, 0],
                [19, 'EU', 'Босния и Герцеговина', 44.25, 17.83, 'Europe/Sarajevo', 'BA', Yii::t('app', 'Bosnia and Herzegovina'), 'Bosnia and Herzegovina', 'BIH', '070', 'yes', '387', '.ba', 8, 'BAM', 0],
                [35, 'AF', 'Ботсвана', -22.00, 24.00, 'Africa/Gaborone', 'BW', Yii::t('app', 'Botswana'), 'Republic of Botswana', 'BWA', '072', 'yes', '267', '.bw', null, 'BWP', 0],
                //[31, 'BV', Yii::t('app', 'Bouvet Island'), 'Bouvet Island', 'BVT', '074', 'no', 'NONE', '.bv', null, null, 0],
                [31, 'SA', 'Бразилия', -10.00, -55.00, 'America/Sao_Paulo', 'BR', Yii::t('app', 'Brazil'), 'Federative Republic of Brazil', 'BRA', '076', 'yes', '55', '.br', 9, 'BRL', 0],
                [104, 'AS', 'Британская территория в Индийском океане', -6.00, 72.00, 'Indian/Chagos', 'IO', Yii::t('app', 'British Indian Ocean Territory'), 'British Indian Ocean Territory', 'IOT', '086', 'no', '246', '.io', 7, 'GBP', 0],
                [29, 'AS', 'Бруней', 4.50, 114.67, 'Asia/Brunei', 'BN', Yii::t('app', 'Brunei'), 'Brunei Darussalam', 'BRN', '096', 'yes', '673', '.bn', null, 'BND', 0],
                [24, 'EU', 'Болгария', 42.67, 25.25, 'Europe/Sofia', 'BG', Yii::t('app', 'Bulgaria'), 'Republic of Bulgaria', 'BGR', '100', 'yes', '359', '.bg', 9, 'BGL', 0],
                [23, 'AF', 'Буркина Фасо', 12.50, -1.67, 'Africa/Ouagadougou', 'BF', Yii::t('app', 'Burkina Faso'), 'Burkina Faso', 'BFA', '854', 'yes', '226', '.bf', 8, 'XAF', 0],
                [26, 'AF', 'Бурунди', -3.50, 30.00, 'Africa/Bujumbura', 'BI', Yii::t('app', 'Burundi'), 'Republic of Burundi', 'BDI', '108', 'yes', '257', '.bi', null, 'BIF', 0],
                [114, 'AS', 'Камбоджа', 13.00, 105.00, 'Asia/Phnom_Penh', 'KH', Yii::t('app', 'Cambodia'), 'Kingdom of Cambodia', 'KHM', '116', 'yes', '855', '.kh', null, 'KHR', 0],
                [47, 'AF', 'Камерун', 6.00, 12.50, 'Africa/Douala', 'CM', Yii::t('app', 'Cameroon'), 'Republic of Cameroon', 'CMR', '120', 'yes', '237', '.cm', null, 'XAF', 0],
                [38, 'NA', 'Канада', 60.11, -113.64, 'America/Toronto', 'CA', Yii::t('app', 'Canada'), 'Canada', 'CAN', '124', 'yes', '1', '.ca', 10, 'CAD', 0],
                //[41, 'CV', Yii::t('app', 'Cape Verde'), 'Republic of Cape Verde', 'CPV', '132', 'yes', '238', '.cv', null, 'CVE', 0],
                [121, 'NA', 'Каймановы острова', 19.50, -80.67, 'America/Cayman', 'KY', Yii::t('app', 'Cayman Islands'), 'The Cayman Islands', 'CYM', '136', 'no', '1-345', '.ky', 10, 'KYD', 0],
                [41, 'AF', 'Центрально-Африканская Республика', 7.00, 21.00, 'Africa/Bangui', 'CF', Yii::t('app', 'Central African Republic'), 'Central African Republic', 'CAF', '140', 'yes', '236', '.cf', null, 'XAF', 0],
                [207, 'AF', 'Чад', 15.00, 19.00, 'Africa/Ndjamena', 'TD', Yii::t('app', 'Chad'), 'Republic of Chad', 'TCD', '148', 'yes', '235', '.td', null, 'XAF', 0],
                [46, 'SA', 'Чили', -30.00, -71.00, 'America/Santiago', 'CL', Yii::t('app', 'Chile'), 'Republic of Chile', 'CHL', '152', 'yes', '56', '.cl', null, 'CLF', 0],
                [48, 'AS', 'Китай', 35.00, 105.00, 'Asia/Shanghai', 'CN', Yii::t('app', 'China'), 'People\'s Republic of China', 'CHN', '156', 'yes', '86', '.cn', 11, 'CNY', 0],
                [53, 'AS', 'Остров Рождества', -10.50, 105.67, 'Indian/Christmas', 'CX', Yii::t('app', 'Christmas Island'), 'Christmas Island', 'CXR', '162', 'no', '61', '.cx', null, 'AUD', 0],
                [39, 'AS', 'Кокосовые острова', -12.16, 96.87, 'Indian/Cocos', 'CC', Yii::t('app', 'Cocos [Keeling] Islands'), 'Cocos [Keeling] Islands', 'CCK', '166', 'no', '61', '.cc', null, 'AUD', 0],
                [49, 'SA', 'Колумбия', 4.00, -73.25, 'America/Bogota', 'CO', Yii::t('app', 'Colombia'), 'Republic of Colombia', 'COL', '170', 'yes', '57', '.co', 10, 'COP', 0],
                [116, 'AF', 'Коморские острова', -12.23, 44.45, 'Indian/Comoro', 'KM', Yii::t('app', 'Comoros'), 'Union of the Comoros', 'COM', '174', 'yes', '269', '.km', null, 'KMF', 0],
                [42, 'AF', 'Конго', -1.00, 15.50, 'Africa/Brazzaville', 'CG', Yii::t('app', 'Congo'), 'Republic of the Congo', 'COG', '178', 'yes', '242', '.cg', null, 'XAF', 0],
                [45, 'OC', 'Острова Кука', -21.25, -159.79, 'Pacific/Rarotonga', 'CK', Yii::t('app', 'Cook Islands'), 'Cook Islands', 'COK', '184', 'some', '682', '.ck', 5, 'NZD', 0],
                [50, 'NA', 'Коста-Рика', 10.00, -84.00, 'America/Costa_Rica', 'CR', Yii::t('app', 'Costa Rica'), 'Republic of Costa Rica', 'CRI', '188', 'yes', '506', '.cr', null, 'CRC', 0],
                [44, 'AF', 'Кот-д’Ивуар', 8.00, -5.50, 'Africa/Abidjan', 'CI', Yii::t('app', 'Cote d\'ivoire [Ivory Coast]'), 'Republic of C&ocirc;te D\'Ivoire [Ivory Coast]', 'CIV', '384', 'yes', '225', '.ci', null, 'XAF', 0],
                [97, 'EU', 'Хорватия', 45.17, 15.50, 'Europe/Zagreb', 'HR', Yii::t('app', 'Croatia'), 'Republic of Croatia', 'HRV', '191', 'yes', '385', '.hr', null, 'HRK', 0],
                [51, 'NA', 'Куба', 22.00, -79.50, 'America/Havana', 'CU', Yii::t('app', 'Cuba'), 'Republic of Cuba', 'CUB', '192', 'yes', '53', '.cu', null, 'CUP', 0],
                //[10, 'NA', 12.17, -68.97, 'America/Curacao', 'CW', Yii::t('app', 'Curacao'), 'Cura&ccedil;ao', 'CUW', '531', 'no', '599', '.cw', null, null, 0],
                [54, 'EU', 'Кипр', 35.00, 33.00, 'Asia/Nicosia', 'CY', Yii::t('app', 'Cyprus'), 'Republic of Cyprus', 'CYP', '196', 'yes', '357', '.cy', 8, 'EUR', 0],
                [55, 'EU', 'Чехия', 49.75, 15.00, 'Europe/Prague', 'CZ', Yii::t('app', 'Czech Republic'), 'Czech Republic', 'CZE', '203', 'yes', '420', '.cz', 9, 'CZK', 0],
                [40, 'AF', 'Демократическая Республика Конго', -2.50, 23.50, 'Africa/Kinshasa', 'CD', Yii::t('app', 'Democratic Republic of the Congo'), 'Democratic Republic of the Congo', 'COD', '180', 'yes', '243', '.cd', null, 'CDZ', 0],
                [58, 'EU', 'Дания', 56.00, 10.00, 'Europe/Copenhagen', 'DK', Yii::t('app', 'Denmark'), 'Kingdom of Denmark', 'DNK', '208', 'yes', '45', '.dk', 8, 'DKK', 0],
                [57, 'AF', 'Джибути', 11.83, 42.50, 'Africa/Djibouti', 'DJ', Yii::t('app', 'Djibouti'), 'Republic of Djibouti', 'DJI', '262', 'yes', '253', '.dj', null, 'DJF', 0],
                [59, 'NA', 'Доминика', 15.50, -61.33, 'America/Dominica', 'DM', Yii::t('app', 'Dominica'), 'Commonwealth of Dominica', 'DMA', '212', 'yes', '1-767', '.dm', 10, 'XCD', 0],
                [60, 'NA', 'Доминиканская республика', 19.00, -70.67, 'America/Santo_Domingo', 'DO', Yii::t('app', 'Dominican Republic'), 'Dominican Republic', 'DOM', '214', 'yes', '1-809', '.do', 10, 'DOP', 0],
                [62, 'SA', 'Эквадор', -1.25, -78.25, 'America/Guayaquil', 'EC', Yii::t('app', 'Ecuador'), 'Republic of Ecuador', 'ECU', '218', 'yes', '593', '.ec', null, 'USD', 0],
                [64, 'AF', 'Египет', 27.00, 30.00, 'Africa/Cairo', 'EG', Yii::t('app', 'Egypt'), 'Arab Republic of Egypt', 'EGY', '818', 'yes', '20', '.eg', 10, 'EGP', 0],
                [203, 'NA', 'Сальвадор', 13.83, -88.92, 'America/El_Salvador', 'SV', Yii::t('app', 'El Salvador'), 'Republic of El Salvador', 'SLV', '222', 'yes', '503', '.sv', null, 'USD', 0],
                [87, 'AF', 'Экваториальная Гвинея', 1.70, 10.50, 'Africa/Malabo', 'GQ', Yii::t('app', 'Equatorial Guinea'), 'Republic of Equatorial Guinea', 'GNQ', '226', 'yes', '240', '.gq', null, 'XAF', 0],
                [66, 'AF', 'Эритрея', 15.00, 39.00, 'Africa/Asmara', 'ER', Yii::t('app', 'Eritrea'), 'State of Eritrea', 'ERI', '232', 'yes', '291', '.er', null, 'ERN', 0],
                [63, 'EU', 'Эстония', 59.00, 26.00, 'Europe/Tallinn', 'EE', Yii::t('app', 'Estonia'), 'Republic of Estonia', 'EST', '233', 'yes', '372', '.ee', null, 'EUR', 0],
                [68, 'AF', 'Эфиопия', 9.00, 39.50, 'Africa/Addis_Ababa', 'ET', Yii::t('app', 'Ethiopia'), 'Federal Democratic Republic of Ethiopia', 'ETH', '231', 'yes', '251', '.et', null, 'ETB', 0],
                [71, 'SA', 'Фолклендские острова', -51.75, -59.17, 'Atlantic/Stanley', 'FK', Yii::t('app', 'Falkland Islands [Malvinas]'), 'The Falkland Islands [Malvinas]', 'FLK', '238', 'no', '500', '.fk', 5, 'FKP', 0],
                [73, 'EU', 'Фарерские острова', 62.00, -7.00, 'Atlantic/Faroe', 'FO', Yii::t('app', 'Faroe Islands'), 'The Faroe Islands', 'FRO', '234', 'no', '298', '.fo', 5, 'DKK', 0],
                [70, 'OC', 'Фиджи', -18.00, 178.00, 'Pacific/Fiji', 'FJ', Yii::t('app', 'Fiji'), 'Republic of Fiji', 'FJI', '242', 'yes', '679', '.fj', null, 'FJD', 0],
                [69, 'EU', 'Финляндия', 64.00, 26.00, 'Europe/Helsinki', 'FI', Yii::t('app', 'Finland'), 'Republic of Finland', 'FIN', '246', 'yes', '358', '.fi', 10, 'EUR', 0],
                [74, 'EU', 'Франция', 46.00, 2.00, 'Europe/Paris', 'FR', Yii::t('app', 'France'), 'French Republic', 'FRA', '250', 'yes', '33', '.fr', 9, 'EUR', 0],
                //[77, 'GF', Yii::t('app', 'French Guiana'), 'French Guiana', 'GUF', '254', 'no', '594', '.gf', null, 'EUR', 0],
                //[78, 'PF', Yii::t('app', 'French Polynesia'), 'French Polynesia', 'PYF', '258', 'no', '689', '.pf', 6, 'XPF', 0],
                //[79, 'TF', 'French Southern Territories', 'French Southern Territories', 'ATF', '260', 'no', NULL, '.tf', null, null, 0],
                [76, 'AF', 'Габон', -1.00, 11.75, 'Africa/Libreville', 'GA', Yii::t('app', 'Gabon'), 'Gabonese Republic', 'GAB', '266', 'yes', '241', '.ga', 7, 'XAF', 0],
                [84, 'AF', 'Гамбия', 13.50, -15.50, 'Africa/Banjul', 'GM', Yii::t('app', 'Gambia'), 'Republic of The Gambia', 'GMB', '270', 'yes', '220', '.gm', null, 'GMD', 0],
                [79, 'AS', 'Грузия', 42.00, 43.50, 'Asia/Tbilisi', 'GE', Yii::t('app', 'Georgia'), 'Georgia', 'GEO', '268', 'yes', '995', '.ge', 9, 'GEL', 0],
                [56, 'EU', 'Германия', 51.50, 10.50, 'Europe/Berlin', 'DE', Yii::t('app', 'Germany'), 'Federal Republic of Germany', 'DEU', '276', 'yes', '49', '.de', 10, 'EUR', 0],
                [81, 'AF', 'Гана', 8.10, -1.20, 'Africa/Accra', 'GH', Yii::t('app', 'Ghana'), 'Republic of Ghana', 'GHA', '288', 'yes', '233', '.gh', 9, 'GHC', 0],
                [82, 'EU', 'Гибралтар', 36.13, -5.35, 'Europe/Gibraltar', 'GI', Yii::t('app', 'Gibraltar'), 'Gibraltar', 'GIB', '292', 'no', '350', '.gi', null, 'GIP', 0],
                [88, 'EU', 'Греция', 39.00, 22.00, 'Europe/Athens', 'GR', Yii::t('app', 'Greece'), 'Hellenic Republic', 'GRC', '300', 'yes', '30', '.gr', 10, 'EUR', 0],
                [83, 'NA', 'Гренландия', 72.00, -40.00, 'America/Godthab', 'GL', Yii::t('app', 'Greenland'), 'Greenland', 'GRL', '304', 'no', '299', '.gl', 6, 'DKK', 0],
                [78, 'NA', 'Гренада', 12.12, -61.67, 'America/Grenada', 'GD', Yii::t('app', 'Grenada'), 'Grenada', 'GRD', '308', 'yes', '1-473', '.gd', 10, 'XCD', 0],
                //[89, 'GP', Yii::t('app', 'Guadaloupe'), 'Guadeloupe', 'GLP', '312', 'no', '590', '.gp', null, null, 0],
                [91, 'OC', 'Гуам', 13.48, 144.82, 'Pacific/Guam', 'GU', Yii::t('app', 'Guam'), 'Guam', 'GUM', '316', 'no', '1-671', '.gu', 10, 'USD', 0],
                [90, 'NA', 'Гватемала', 15.50, -90.25, 'America/Guatemala', 'GT', Yii::t('app', 'Guatemala'), 'Republic of Guatemala', 'GTM', '320', 'yes', '502', '.gt', null, 'GTQ', 0],
                //[92, 'GG', Yii::t('app', 'Guernsey'), 'Guernsey', 'GGY', '831', 'no', '44', '.gg', 10, null, 0],
                [85, 'AF', 'Гвинея', 10.83, -10.67, 'Africa/Conakry', 'GN', Yii::t('app', 'Guinea'), 'Republic of Guinea', 'GIN', '324', 'yes', '224', '.gn', null, 'GNS', 0],
                [92, 'AF', 'Гвинея-Бисау', 12.00, -15.00, 'Africa/Bissau', 'GW', Yii::t('app', 'Guinea-Bissau'), 'Republic of Guinea-Bissau', 'GNB', '624', 'yes', '245', '.gw', null, 'GWP', 0],
                [93, 'SA', 'Гайана', 5.00, -59.00, 'America/Guyana', 'GY', Yii::t('app', 'Guyana'), 'Co-operative Republic of Guyana', 'GUY', '328', 'yes', '592', '.gy', null, 'GYD', 0],
                [98, 'NA', 'Гаити', 19.00, -72.42, 'America/Port-au-Prince', 'HT', Yii::t('app', 'Haiti'), 'Republic of Haiti', 'HTI', '332', 'yes', '509', '.ht', null, 'HTG', 0],
                //[97, 'HM', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HMD', '334', 'no', 'NONE', '.hm', null, null, 0],
                [96, 'NA', 'Гондурас', 15.00, -86.50, 'America/Tegucigalpa', 'HN', Yii::t('app', 'Honduras'), 'Republic of Honduras', 'HND', '340', 'yes', '504', '.hn', null, 'HNL', 0],
                [94, 'AS', 'Гонконг', 22.25, 114.17, 'Asia/Hong_Kong', 'HK', Yii::t('app', 'Hong Kong'), 'Hong Kong', 'HKG', '344', 'no', '852', '.hk', 8, 'HKD', 0],
                [99, 'EU', 'Венгрия', 47.00, 20.00, 'Europe/Budapest', 'HU', Yii::t('app', 'Hungary'), 'Hungary', 'HUN', '348', 'yes', '36', '.hu', 9, 'HUF', 0],
                [107, 'EU', 'Исландия', 65.00, -18.00, 'Atlantic/Reykjavik', 'IS', Yii::t('app', 'Iceland'), 'Republic of Iceland', 'ISL', '352', 'yes', '354', '.is', null, 'ISK', 0],
                [103, 'AS', 'Индия', 22.00, 79.00, 'Asia/Kolkata', 'IN', Yii::t('app', 'India'), 'Republic of India', 'IND', '356', 'yes', '91', '.in', 10, 'INR', 0],
                [100, 'AS', 'Индонезия', -5.00, 120.00, 'Asia/Jakarta', 'ID', Yii::t('app', 'Indonesia'), 'Republic of Indonesia', 'IDN', '360', 'yes', '62', '.id', 11, 'IDR', 0],
                [106, 'AS', 'Иран', 32.00, 53.00, 'Asia/Tehran', 'IR', Yii::t('app', 'Iran'), 'Islamic Republic of Iran', 'IRN', '364', 'yes', '98', '.ir', 10, 'IRR', 0],
                [105, 'AS', 'Ирак', 33.00, 44.00, 'Asia/Baghdad', 'IQ', Yii::t('app', 'Iraq'), 'Republic of Iraq', 'IRQ', '368', 'yes', '964', '.iq', null, 'IQD', 0],
                [101, 'EU', 'Ирландия', 53.00, -8.00, 'Europe/Dublin', 'IE', Yii::t('app', 'Ireland'), 'Ireland', 'IRL', '372', 'yes', '353', '.ie', 9, 'EUR', 0],
                //[107, 'IM', Yii::t('app', 'Isle of Man'), 'Isle of Man', 'IMN', '833', 'no', '44', '.im', 10, null, 0],
                [102, 'AS', 'Израиль', 31.50, 34.75, 'Asia/Jerusalem', 'IL', Yii::t('app', 'Israel'), 'State of Israel', 'ISR', '376', 'yes', '972', '.il', 9, 'ILS', 0],
                [108, 'EU', 'Италия', 42.83, 12.83, 'Europe/Rome', 'IT', Yii::t('app', 'Italy'), 'Italian Republic', 'ITA', '380', 'yes', '39', '.jm', 10, 'EUR', 0],
                [109, 'NA', 'Ямайка', 18.17, -77.25, 'America/Jamaica', 'JM', Yii::t('app', 'Jamaica'), 'Jamaica', 'JAM', '388', 'yes', '1-876', '.jm', 10, 'JMD', 0],
                [111, 'AS', 'Япония', 35.69, 139.75, 'Asia/Tokyo', 'JP', Yii::t('app', 'Japan'), 'Japan', 'JPN', '392', 'yes', '81', '.jp', null, 'JPY', 0],
                //[112, 'JE', Yii::t('app', 'Jersey'), 'The Bailiwick of Jersey', 'JEY', '832', 'no', '44', '.je', 10, null, 0],
                [110, 'AS', 'Иордания', 31.00, 36.00, 'Asia/Amman', 'JO', Yii::t('app', 'Jordan'), 'Hashemite Kingdom of Jordan', 'JOR', '400', 'yes', '962', '.jo', null, 'JOD', 0],
                [122, 'AS', 'Казахстан', 48.00, 68.00, 'Asia/Almaty', 'KZ', Yii::t('app', 'Kazakhstan'), 'Republic of Kazakhstan', 'KAZ', '398', 'yes', '7', '.kz', 9, 'KZT', 0],
                [112, 'AF', 'Кения', 1.00, 38.00, 'Africa/Nairobi', 'KE', Yii::t('app', 'Kenya'), 'Republic of Kenya', 'KEN', '404', 'yes', '254', '.ke', null, 'KES', 0],
                [115, 'OC', 'Кирибати', 1.42, 172.98, 'Pacific/Tarawa', 'KI', Yii::t('app', 'Kiribati'), 'Republic of Kiribati', 'KIR', '296', 'yes', '686', '.ki', 5, 'AUD', 0],
                //[117, 'XK', Yii::t('app', 'Kosovo'), 'Republic of Kosovo', '---', '---', 'some', '381', '', null, null, 0],
                [120, 'AS', 'Кувейт', 29.50, 47.75, 'Asia/Kuwait', 'KW', Yii::t('app', 'Kuwait'), 'State of Kuwait', 'KWT', '414', 'yes', '965', '.kw', null, 'KWD', 0],
                [113, 'AS', 'Кыргызстан', 41.50, 75.00, 'Asia/Bishkek', 'KG', Yii::t('app', 'Kyrgyzstan'), 'Kyrgyz Republic', 'KGZ', '417', 'yes', '996', '.kg', null, 'KGS', 0],
                [123, 'AS', 'Лаос', 18.00, 105.00, 'Asia/Vientiane', 'LA', Yii::t('app', 'Laos'), 'Lao People\'s Democratic Republic', 'LAO', '418', 'yes', '856', '.la', null, 'LAK', 0],
                [132, 'EU', 'Латвия', 57.00, 25.00, 'Europe/Riga', 'LV', Yii::t('app', 'Latvia'), 'Republic of Latvia', 'LVA', '428', 'yes', '371', '.lv', 8, 'EUR', 0],
                [124, 'AS', 'Ливан', 33.83, 35.83, 'Asia/Beirut', 'LB', Yii::t('app', 'Lebanon'), 'Republic of Lebanon', 'LBN', '422', 'yes', '961', '.lb', null, 'LBP', 0],
                [129, 'AF', 'Лесото', -29.50, 28.25, 'Africa/Maseru', 'LS', Yii::t('app', 'Lesotho'), 'Kingdom of Lesotho', 'LSO', '426', 'yes', '266', '.ls', null, 'LSL', 0],
                [128, 'AF', 'Либерия', 6.50, -9.50, 'Africa/Monrovia', 'LR', Yii::t('app', 'Liberia'), 'Republic of Liberia', 'LBR', '430', 'yes', '231', '.lr', 7, 'LRD', 1],
                [133, 'AF', 'Ливия', 28.00, 17.00, 'Africa/Tripoli', 'LY', Yii::t('app', 'Libya'), 'Libya', 'LBY', '434', 'yes', '218', '.ly', null, 'LYD', 0],
                [126, 'EU', 'Лихтенштейн', 47.17, 9.53, 'Europe/Vaduz', 'LI', Yii::t('app', 'Liechtenstein'), 'Principality of Liechtenstein', 'LIE', '438', 'yes', '423', '.li', null, 'CHF', 0],
                [130, 'EU', 'Литва', 55.42, 24.00, 'Europe/Vilnius', 'LT', Yii::t('app', 'Lithuania'), 'Republic of Lithuania', 'LTU', '440', 'yes', '370', '.lt', null, 'EUR', 0],
                [131, 'EU', 'Люксембург', 49.75, 6.17, 'Europe/Luxembourg', 'LU', Yii::t('app', 'Luxembourg'), 'Grand Duchy of Luxembourg', 'LUX', '442', 'yes', '352', '.lu', 9, 'EUR', 0],
                [143, 'AS', 'Макау', 22.16, 113.56, 'Asia/Macau', 'MO', Yii::t('app', 'Macao'), 'The Macao Special Administrative Region', 'MAC', '446', 'no', '853', '.mo', null, 'MOP', 0],
                [139, 'EU', 'Македония', 41.67, 21.75, 'Europe/Skopje', 'MK', Yii::t('app', 'Macedonia'), 'The Former Yugoslav Republic of Macedonia', 'MKD', '807', 'yes', '389', '.mk', 8, 'MKD', 0],
                [137, 'AF', 'Мадагаскар', -20.00, 47.00, 'Indian/Antananarivo', 'MG', Yii::t('app', 'Madagascar'), 'Republic of Madagascar', 'MDG', '450', 'yes', '261', '.mg', null, 'MGF', 0],
                [151, 'AF', 'Малави', -13.50, 34.00, 'Africa/Blantyre', 'MW', Yii::t('app', 'Malawi'), 'Republic of Malawi', 'MWI', '454', 'yes', '265', '.mw', null, 'MWK', 0],
                [153, 'AS', 'Малайзия', 2.50, 112.50, 'Asia/Kuala_Lumpur', 'MY', Yii::t('app', 'Malaysia'), 'Malaysia', 'MYS', '458', 'yes', '60', '.my', null, 'MYR', 0],
                [150, 'AS', 'Мальдивские острова', 3.20, 73.00, 'Indian/Maldives', 'MV', Yii::t('app', 'Maldives'), 'Republic of Maldives', 'MDV', '462', 'yes', '960', '.mv', null, 'MVR', 0],
                [140, 'AF', 'Мали', 18.00, -2.00, 'Africa/Bamako', 'ML', Yii::t('app', 'Mali'), 'Republic of Mali', 'MLI', '466', 'yes', '223', '.ml', 8, 'XAF', 0],
                [148, 'EU', 'Мальта', 35.92, 14.43, 'Europe/Malta', 'MT', Yii::t('app', 'Malta'), 'Republic of Malta', 'MLT', '470', 'yes', '356', '.mt', null, 'EUR', 0],
                //[137, 'MH', Yii::t('app', 'Marshall Islands'), 'Republic of the Marshall Islands', 'MHL', '584', 'yes', '692', '.mh', 7, 'USD', 0],
                [145, 'NA', 'Мартиника', 14.67, -61.00, 'America/Martinique', 'MQ', Yii::t('app', 'Martinique'), 'Martinique', 'MTQ', '474', 'no', '596', '.mq', null, 'EUR', 0],
                [146, 'AF', 'Мавритания', 20.25, -10.50, 'Africa/Nouakchott', 'MR', Yii::t('app', 'Mauritania'), 'Islamic Republic of Mauritania', 'MRT', '478', 'yes', '222', '.mr', null, 'MRO', 0],
                [149, 'AF', 'Маврикий', -20.30, 57.58, 'Indian/Mauritius', 'MU', Yii::t('app', 'Mauritius'), 'Republic of Mauritius', 'MUS', '480', 'yes', '230', '.mu', null, 'MUR', 0],
                [238, 'AF', 'Майотта', -12.83, 45.17, 'Indian/Mayotte', 'YT', Yii::t('app', 'Mayotte'), 'Mayotte', 'MYT', '175', 'no', '262', '.yt', null, 'EUR', 0],
                [152, 'NA', 'Мексика', 23.00, -102.00, 'America/Mexico_City', 'MX', Yii::t('app', 'Mexico'), 'United Mexican States', 'MEX', '484', 'yes', '52', '.mx', 10, 'MXN', 0],
                //[143, 'FM', Yii::t('app', 'Micronesia'), 'Federated States of Micronesia', 'FSM', '583', 'yes', '691', '.fm', 7, 'USD', 0],
                [136, 'EU', 'Молдова', 47.25, 28.58, 'Europe/Chisinau', 'MD', Yii::t('app', 'Moldova'), 'Republic of Moldova', 'MDA', '498', 'yes', '373', '.md', 8, 'MDL', 0],
                [135, 'EU', 'Монако', 43.73, 7.42, 'Europe/Monaco', 'MC', Yii::t('app', 'Monaco'), 'Principality of Monaco', 'MCO', '492', 'yes', '377', '.mc', null, 'EUR', 0],
                [142, 'AS', 'Монголия', 46.00, 105.00, 'Asia/Ulaanbaatar', 'MN', Yii::t('app', 'Mongolia'), 'Mongolia', 'MNG', '496', 'yes', '976', '.mn', 8, 'MNT', 0],
                //[147, 'ME', Yii::t('app', 'Montenegro'), 'Montenegro', 'MNE', '499', 'yes', '382', '.me', 8, null, 0],
                [147, 'NA', 'Монтсеррат', 16.75, -62.20, 'America/Montserrat', 'MS', Yii::t('app', 'Montserrat'), 'Montserrat', 'MSR', '500', 'no', '1-664', '.ms', 10, 'XCD', 0],
                [134, 'AF', 'Марокко', 32.00, -6.00, 'Africa/Casablanca', 'MA', Yii::t('app', 'Morocco'), 'Kingdom of Morocco', 'MAR', '504', 'yes', '212', '.ma', null, 'MAD', 0],
                [154, 'AF', 'Мозамбик', -18.25, 35.00, 'Africa/Maputo', 'MZ', Yii::t('app', 'Mozambique'), 'Republic of Mozambique', 'MOZ', '508', 'yes', '258', '.mz', null, 'MZM', 0],
                //[151, 'MM', Yii::t('app', 'Myanmar [Burma]'), 'Republic of the Union of Myanmar', 'MMR', '104', 'yes', '95', '.mm', null, 'MMK', 0],
                [155, 'AF', 'Намибия', -22.00, 17.00, 'Africa/Windhoek', 'NA', Yii::t('app', 'Namibia'), 'Republic of Namibia', 'NAM', '516', 'yes', '264', '.na', null, 'NAD', 0],
                [164, 'OC', 'Науру', -0.52, 166.93, 'Pacific/Nauru', 'NR', Yii::t('app', 'Nauru'), 'Republic of Nauru', 'NRU', '520', 'yes', '674', '.nr', null, 'AUD', 0],
                [163, 'AS', 'Непал', 28.00, 84.00, 'Asia/Kathmandu', 'NP', Yii::t('app', 'Nepal'), 'Federal Democratic Republic of Nepal', 'NPL', '524', 'yes', '977', '.np', null, 'NPR', 0],
                [161, 'EU', 'Нидерланды', 52.25, 5.75, 'Europe/Amsterdam', 'NL', Yii::t('app', 'Netherlands'), 'Kingdom of the Netherlands', 'NLD', '528', 'yes', '31', '.nl', 9, 'EUR', 0],
                //[156, 'NC', Yii::t('app', 'New Caledonia'), 'New Caledonia', 'NCL', '540', 'no', '687', '.nc', 6, 'XPF', 0],
                [166, 'OC', 'Новая Зеландия', -42.00, 174.00, 'Pacific/Auckland', 'NZ', Yii::t('app', 'New Zealand'), 'New Zealand', 'NZL', '554', 'yes', '64', '.nz', null, 'NZD', 0],
                [160, 'NA', 'Никарагуа', 13.00, -85.00, 'America/Managua', 'NI', Yii::t('app', 'Nicaragua'), 'Republic of Nicaragua', 'NIC', '558', 'yes', '505', '.ni', null, 'NIC', 0],
                [157, 'AF', 'Нигер', 18.00, 9.00, 'Africa/Niamey', 'NE', Yii::t('app', 'Niger'), 'Republic of Niger', 'NER', '562', 'yes', '227', '.ne', 8, 'XOF', 0],
                [159, 'AF', 'Нигерия', 10.00, 8.00, 'Africa/Lagos', 'NG', Yii::t('app', 'Nigeria'), 'Federal Republic of Nigeria', 'NGA', '566', 'yes', '234', '.ng', null, 'NGN', 0],
                [165, 'OC', 'Ниуэ', -19.03, -169.87, 'Pacific/Niue', 'NU', Yii::t('app', 'Niue'), 'Niue', 'NIU', '570', 'some', '683', '.nu', 4, 'NZD', 0],
                [158, 'OC', 'Норфолк', -29.03, 167.95, 'Pacific/Norfolk', 'NF', Yii::t('app', 'Norfolk Island'), 'Norfolk Island', 'NFK', '574', 'no', '672', '.nf', 6, 'AUD', 0],
                [118, 'AS', 'Северная Корея', 40.00, 127.00, 'Asia/Pyongyang', 'KP', Yii::t('app', 'North Korea'), 'Democratic People\'s Republic of Korea', 'PRK', '408', 'yes', '850', '.kp', null, 'KPW', 0],
                [144, 'OC', 'Северные Марианские острова', 15.21, 145.76, 'Pacific/Saipan', 'MP', Yii::t('app', 'Northern Mariana Islands'), 'Northern Mariana Islands', 'MNP', '580', 'no', '1-670', '.mp', 10, 'USD', 0],
                [162, 'EU', 'Норвегия', 62.00, 10.00, 'Europe/Oslo', 'NO', Yii::t('app', 'Norway'), 'Kingdom of Norway', 'NOR', '578', 'yes', '47', '.no', 8, 'NOK', 0],
                [167, 'AS', 'Оман', 21.00, 57.00, 'Asia/Muscat', 'OM', Yii::t('app', 'Oman'), 'Sultanate of Oman', 'OMN', '512', 'yes', '968', '.om', null, 'OMR', 0],
                [173, 'AS', 'Пакистан', 30.00, 70.00, 'Asia/Karachi', 'PK', Yii::t('app', 'Pakistan'), 'Islamic Republic of Pakistan', 'PAK', '586', 'yes', '92', '.pk', 10, 'PKR', 0],
                [180, 'OC', 'Палау', 7.50, 134.62, 'Pacific/Palau', 'PW', Yii::t('app', 'Palau'), 'Republic of Palau', 'PLW', '585', 'yes', '680', '.pw', 7, 'USD', 0],
                //[169, 'PS', Yii::t('app', 'Palestine'), 'State of Palestine [or Occupied Palestinian Territory]', 'PSE', '275', 'some', '970', '.ps', null, null, 0],
                [168, 'NA', 'Панама', 9.00, -80.00, 'America/Panama', 'PA', Yii::t('app', 'Panama'), 'Republic of Panama', 'PAN', '591', 'yes', '507', '.pa', 8, 'PAB', 0],
                [171, 'OC', 'Папуа Новая Гвинея', -6.00, 147.00, 'Pacific/Port_Moresby', 'PG', Yii::t('app', 'Papua New Guinea'), 'Independent State of Papua New Guinea', 'PNG', '598', 'yes', '675', '.pg', null, 'PGK', 0],
                [181, 'SA', 'Парагвай', -23.33, -58.00, 'America/Asuncion', 'PY', Yii::t('app', 'Paraguay'), 'Republic of Paraguay', 'PRY', '600', 'yes', '595', '.py', null, 'PYG', 0],
                [169, 'SA', 'Перу', -10.00, -75.25, 'America/Lima', 'PE', Yii::t('app', 'Peru'), 'Republic of Peru', 'PER', '604', 'yes', '51', '.pe', null, 'PEI', 0],
                [172, 'AS', 'Филиппины', 13.00, 122.00, 'Asia/Manila', 'PH', Yii::t('app', 'Phillipines'), 'Republic of the Philippines', 'PHL', '608', 'yes', '63', '.ph', 10, 'PHP', 0],
                //[175, 'PN', Yii::t('app', 'Pitcairn'), 'Pitcairn', 'PCN', '612', 'no', 'NONE', '.pn', null, null, 0],
                [174, 'EU', 'Польша', 52.00, 20.00, 'Europe/Warsaw', 'PL', Yii::t('app', 'Poland'), 'Republic of Poland', 'POL', '616', 'yes', '48', '.pl', 9, 'PLN', 0],
                [179, 'EU', 'Португалия', 39.69, -8.13, 'Europe/Lisbon', 'PT', Yii::t('app', 'Portugal'), 'Portuguese Republic', 'PRT', '620', 'yes', '351', '.pt', 9, 'EUR', 0],
                [177, 'NA', 'Пуэрто Рико', 18.25, -66.50, 'America/Puerto_Rico', 'PR', Yii::t('app', 'Puerto Rico'), 'Commonwealth of Puerto Rico', 'PRI', '630', 'no', '1-939', '.pr', 10, 'USD', 0],
                [182, 'AS', 'Катар', 25.50, 51.25, 'Asia/Qatar', 'QA', Yii::t('app', 'Qatar'), 'State of Qatar', 'QAT', '634', 'yes', '974', '.qa', null, 'QAR', 0],
                [183, 'AF', 'Реюньон', -21.10, 55.60, 'Indian/Reunion', 'RE', Yii::t('app', 'Reunion'), 'R&eacute;union', 'REU', '638', 'no', '262', '.re', null, 'EUR', 0],
                [184, 'EU', 'Румыния', 46.00, 25.00, 'Europe/Bucharest', 'RO', Yii::t('app', 'Romania'), 'Romania', 'ROU', '642', 'yes', '40', '.ro', null, 'ROL', 0],
                [185, 'EU', 'Россия', 60.00, 100.00, 'Europe/Moscow', 'RU', Yii::t('app', 'Russia'), 'Russian Federation', 'RUS', '643', 'yes', '7', '.ru', 10, 'RUB', 0],
                [186, 'AF', 'Руанда', -2.00, 30.00, 'Africa/Kigali', 'RW', Yii::t('app', 'Rwanda'), 'Republic of Rwanda', 'RWA', '646', 'yes', '250', '.rw', null, 'RWF', 0],
                [251, 'NA', 'Сен-Бартелеми', 17.90, -62.83, 'America/St_Barthelemy', 'BL', Yii::t('app', 'Saint Barthelemy'), 'Saint Barth&eacute;lemy', 'BLM', '652', 'no', '590', '.bl', null, 'EUR', 0],
                //[185, 'SH', Yii::t('app', 'Saint Helena'), 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '654', 'no', '290', '.sh', 4, 'SHP', 0],
                [117, 'NA', 'Сент Китс и Невис', 17.33, -62.75, 'America/St_Kitts', 'KN', Yii::t('app', 'Saint Kitts and Nevis'), 'Federation of Saint Christopher and Nevis', 'KNA', '659', 'yes', '1-869', '.kn', 10, 'XCD', 0],
                [125, 'NA', 'Святая Люсия', 13.88, -60.97, 'America/St_Lucia', 'LC', Yii::t('app', 'Saint Lucia'), 'Saint Lucia', 'LCA', '662', 'yes', '1-758', '.lc', 10, 'XCD', 0],
                [252, 'NA', 'Сен-Мартен', 18.07, -63.07, 'America/Marigot', 'MF', Yii::t('app', 'Saint Martin'), 'Saint Martin', 'MAF', '663', 'no', '590', '.mf', null, 'EUR', 0],
                [175, 'NA', 'Сен-Пьер и Микелон', 46.83, -56.33, 'America/Miquelon', 'PM', Yii::t('app', 'Saint Pierre and Miquelon'), 'Saint Pierre and Miquelon', 'SPM', '666', 'no', '508', '.pm', null, 'EUR', 0],
                [229, 'NA', 'Сент-Винсент и Гренадины', 13.08, -61.20, 'America/St_Vincent', 'VC', Yii::t('app', 'Saint Vincent and the Grenadines'), 'Saint Vincent and the Grenadines', 'VCT', '670', 'yes', '1-784', '.vc', 10, 'XCD', 0],
                [236, 'OC', 'Самоа', -13.80, -172.13, 'Pacific/Apia', 'WS', Yii::t('app', 'Samoa'), 'Independent State of Samoa', 'WSM', '882', 'yes', '685', '.ws', null, 'WST', 0],
                [198, 'EU', 'Сан-Марино', 43.94, 12.45, 'Europe/San_Marino', 'SM', Yii::t('app', 'San Marino'), 'Republic of San Marino', 'SMR', '674', 'yes', '378', '.sm', null, 'EUR', 0],
                [202, 'AF', 'Сан-Томе и Принсипи', 1.00, 7.00, 'Africa/Sao_Tome', 'ST', Yii::t('app', 'Sao Tome and Principe'), 'Democratic Republic of S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'STP', '678', 'yes', '239', '.st', null, 'STD', 0],
                [187, 'AS', 'Саудовская Аравия', 25.00, 45.00, 'Asia/Riyadh', 'SA', Yii::t('app', 'Saudi Arabia'), 'Kingdom of Saudi Arabia', 'SAU', '682', 'yes', '966', '.sa', 10, 'SAR', 0],
                [199, 'AF', 'Сенегал', 14.50, -14.25, 'Africa/Dakar', 'SN', Yii::t('app', 'Senegal'), 'Republic of Senegal', 'SEN', '686', 'yes', '221', '.sn', null, 'XOF', 0],
                //[196, 'RS', Yii::t('app', 'Serbia'), 'Republic of Serbia', 'SRB', '688', 'yes', '381', '.rs', 9, null, 0],
                [189, 'AF', 'Сейшеллы', -4.58, 55.67, 'Indian/Mahe', 'SC', Yii::t('app', 'Seychelles'), 'Republic of Seychelles', 'SYC', '690', 'yes', '248', '.sc', null, 'SCR', 0],
                [197, 'AF', 'Сьерра-Леоне', 8.50, -11.50, 'Africa/Freetown', 'SL', Yii::t('app', 'Sierra Leone'), 'Republic of Sierra Leone', 'SLE', '694', 'yes', '232', '.sl', null, 'SLL', 0],
                [192, 'AS', 'Сингапур', 1.37, 103.80, 'Asia/Singapore', 'SG', Yii::t('app', 'Singapore'), 'Republic of Singapore', 'SGP', '702', 'yes', '65', '.sg', null, 'SGD', 0],
                //[200, 'SX', Yii::t('app', 'Sint Maarten'), 'Sint Maarten', 'SXM', '534', 'no', '1-721', '.sx', 10, null, 0],
                [196, 'EU', 'Словакия', 48.67, 19.50, 'Europe/Bratislava', 'SK', Yii::t('app', 'Slovakia'), 'Slovak Republic', 'SVK', '703', 'yes', '421', '.sk', 9, 'EUR', 0],
                [194, 'EU', 'Словения', 46.08, 15.00, 'Europe/Ljubljana', 'SI', Yii::t('app', 'Slovenia'), 'Republic of Slovenia', 'SVN', '705', 'yes', '386', '.si', null, 'EUR', 0],
                [188, 'OC', 'Соломоновы острова', -8.00, 159.00, 'Pacific/Guadalcanal', 'SB', Yii::t('app', 'Solomon Islands'), 'Solomon Islands', 'SLB', '090', 'yes', '677', '.sb', 7, 'SBD', 0],
                [200, 'AF', 'Сомали', 6.00, 48.00, 'Africa/Mogadishu', 'SO', Yii::t('app', 'Somalia'), 'Somali Republic', 'SOM', '706', 'yes', '252', '.so', null, 'SOS', 0],
                [240, 'AF', 'ЮАР', -29.00, 24.00, 'Africa/Johannesburg', 'ZA', Yii::t('app', 'South Africa'), 'Republic of South Africa', 'ZAF', '710', 'yes', '27', '.za', 9, 'ZAR', 0],
                [89, 'AN', 'Южная Георгия и Южные Сандвичевы острова', -56.00, -33.00, 'Atlantic/South_Georgia', 'GS', Yii::t('app', 'South Georgia and the South Sandwich Islands'), 'South Georgia and the South Sandwich Islands', 'SGS', '239', 'no', '500', '.gs', null, 'GBP', 0],
                [119, 'AS', 'Южная Корея', 36.50, 127.75, 'Asia/Seoul', 'KR', Yii::t('app', 'South Korea'), 'Republic of Korea', 'KOR', '410', 'yes', '82', '.kr', null, 'KRW', 0],
                //[208, 'SS', Yii::t('app', 'South Sudan'), 'Republic of South Sudan', 'SSD', '728', 'yes', '211', '.ss', null, null, 0],
                [67, 'EU', 'Испания', 40.00, -4.00, 'Europe/Madrid', 'ES', Yii::t('app', 'Spain'), 'Kingdom of Spain', 'ESP', '724', 'yes', '34', '.es', 9, 'EUR', 0],
                [127, 'AS', 'Шри-Ланка', 7.75, 80.75, 'Asia/Colombo', 'LK', Yii::t('app', 'Sri Lanka'), 'Democratic Socialist Republic of Sri Lanka', 'LKA', '144', 'yes', '94', '.lk', 7, 'LKR', 0],
                [190, 'AF', 'Судан', 16.00, 30.00, 'Africa/Khartoum', 'SD', Yii::t('app', 'Sudan'), 'Republic of the Sudan', 'SDN', '729', 'yes', '249', '.sd', null, 'SDG', 0],
                [201, 'SA', 'Суринам', 4.00, -56.00, 'America/Paramaribo', 'SR', Yii::t('app', 'Suriname'), 'Republic of Suriname', 'SUR', '740', 'yes', '597', '.sr', null, 'SRG', 0],
                [195, 'EU', 'Свальбард и Ян-Майен', 78.00, 20.00, 'Arctic/Longyearbyen', 'SJ', Yii::t('app', 'Svalbard and Jan Mayen'), 'Svalbard and Jan Mayen', 'SJM', '744', 'no', '47', '.sj', null, 'NOK', 0],
                [205, 'AF', 'Свазиленд', -26.50, 31.50, 'Africa/Mbabane', 'SZ', Yii::t('app', 'Swaziland'), 'Kingdom of Swaziland', 'SWZ', '748', 'yes', '268', '.sz', null, 'SZL', 0],
                [191, 'EU', 'Швеция', 62.00, 15.00, 'Europe/Stockholm', 'SE', Yii::t('app', 'Sweden'), 'Kingdom of Sweden', 'SWE', '752', 'yes', '46', '.se', null, 'SEK', 0],
                [43, 'EU', 'Швейцария', 47.00, 8.01, 'Europe/Zurich', 'CH', Yii::t('app', 'Switzerland'), 'Swiss Confederation', 'CHE', '756', 'yes', '41', '.ch', 9, 'CHF', 0],
                [204, 'AS', 'Сирия', 35.00, 38.00, 'Asia/Damascus', 'SY', Yii::t('app', 'Syria'), 'Syrian Arab Republic', 'SYR', '760', 'yes', '963', '.sy', null, 'SYP', 0],
                [220, 'AS', 'Тайвань', 24.00, 121.00, 'Asia/Taipei', 'TW', Yii::t('app', 'Taiwan'), 'Republic of China [Taiwan]', 'TWN', '158', 'former', '886', '.tw', 9, 'TWD', 0],
                [211, 'AS', 'Таджикистан', 39.00, 71.00, 'Asia/Dushanbe', 'TJ', Yii::t('app', 'Tajikistan'), 'Republic of Tajikistan', 'TJK', '762', 'yes', '992', '.tj', null, 'TJR', 0],
                [221, 'AF', 'Танзания', -6.00, 35.00, 'Africa/Dar_es_Salaam', 'TZ', Yii::t('app', 'Tanzania'), 'United Republic of Tanzania', 'TZA', '834', 'yes', '255', '.tz', null, 'TZS', 0],
                [210, 'AS', 'Таиланд', 15.50, 101.00, 'Asia/Bangkok', 'TH', Yii::t('app', 'Thailand'), 'Kingdom of Thailand', 'THA', '764', 'yes', '66', '.th', 9, 'THB', 0],
                //[222, 'TL', Yii::t('app', 'Timor-Leste [East Timor]'), 'Democratic Republic of Timor-Leste', 'TLS', '626', 'yes', '670', '.tl', 8, null, 0],
                [209, 'AF', 'Того', 8.67, 1.08, 'Africa/Lome', 'TG', Yii::t('app', 'Togo'), 'Togolese Republic', 'TGO', '768', 'yes', '228', '.tg', 8, 'XAF', 0],
                [212, 'OC', 'Токелау', -9.17, -171.83, 'Pacific/Fakaofo', 'TK', Yii::t('app', 'Tokelau'), 'Tokelau', 'TKL', '772', 'no', '690', '.tk', null, 'NZD', 0],
                [215, 'OC', 'Тонга', -20.00, -175.00, 'Pacific/Tongatapu', 'TO', Yii::t('app', 'Tonga'), 'Kingdom of Tonga', 'TON', '776', 'yes', '676', '.to', null, 'TOP', 0],
                [218, 'NA', 'Тринидад и Тобаго', 11.00, -61.00, 'America/Port_of_Spain', 'TT', Yii::t('app', 'Trinidad and Tobago'), 'Republic of Trinidad and Tobago', 'TTO', '780', 'yes', '1-868', '.tt', 10, 'TTD', 0],
                [214, 'AF', 'Тунис', 34.00, 9.00, 'Africa/Tunis', 'TN', Yii::t('app', 'Tunisia'), 'Republic of Tunisia', 'TUN', '788', 'yes', '216', '.tn', null, 'TND', 0],
                [217, 'AS', 'Турция', 39.00, 35.00, 'Europe/Istanbul', 'TR', Yii::t('app', 'Turkey'), 'Republic of Turkey', 'TUR', '792', 'yes', '90', '.tr', 10, 'TRY', 0],
                [213, 'AS', 'Туркменистан', 39.75, 59.67, 'Asia/Ashgabat', 'TM', Yii::t('app', 'Turkmenistan'), 'Turkmenistan', 'TKM', '795', 'yes', '993', '.tm', null, 'TMM', 0],
                [206, 'NA', 'Туркс и Кейкос', 21.73, -71.58, 'America/Grand_Turk', 'TC', Yii::t('app', 'Turks and Caicos Islands'), 'Turks and Caicos Islands', 'TCA', '796', 'no', '1-649', '.tc', 10, 'USD', 0],
                [219, 'OC', 'Тувалу', -8.52, 179.14, 'Pacific/Funafuti', 'TV', Yii::t('app', 'Tuvalu'), 'Tuvalu', 'TUV', '798', 'yes', '688', '.tv', null, 'AUD', 0],
                [223, 'AF', 'Уганда', 1.25, 32.50, 'Africa/Kampala', 'UG', Yii::t('app', 'Uganda'), 'Republic of Uganda', 'UGA', '800', 'yes', '256', '.ug', null, 'UGS', 0],
                [222, 'EU', 'Украина', 49.00, 32.00, 'Europe/Kiev', 'UA', Yii::t('app', 'Ukraine'), 'Ukraine', 'UKR', '804', 'yes', '380', '.ua', 9, 'UAH', 0],
                [4, 'AS', 'ОАЭ', 23.75, 54.50, 'Asia/Dubai', 'AE', Yii::t('app', 'United Arab Emirates'), 'United Arab Emirates', 'ARE', '784', 'yes', '971', '.ae', 10, 'AED', 0],
                [77, 'EU', 'Великобритания', 54.76, -2.70, 'Europe/London', 'GB', Yii::t('app', 'United Kingdom'), 'United Kingdom of Great Britain and Nothern Ireland', 'GBR', '826', 'yes', '44', '.uk', 10, 'GBP', 1],
                [225, 'NA', 'США', 39.76, -98.50, 'America/New_York', 'US', Yii::t('app', 'United States'), 'United States of America', 'USA', '840', 'yes', '1', '.us', 10, 'USD', 1],
                //[237, 'UM', Yii::t('app', 'United States Minor Outlying Islands'), 'United States Minor Outlying Islands', 'UMI', '581', 'no', 'NONE', 'NONE', null, null, 0],
                [226, 'SA', 'Уругвай', -33.00, -56.00, 'America/Montevideo', 'UY', Yii::t('app', 'Uruguay'), 'Eastern Republic of Uruguay', 'URY', '858', 'yes', '598', '.uy', null, 'UYU', 0],
                [227, 'AS', 'Узбекистан', 41.67, 63.83, 'Asia/Tashkent', 'UZ', Yii::t('app', 'Uzbekistan'), 'Republic of Uzbekistan', 'UZB', '860', 'yes', '998', '.uz', null, 'UZS', 0],
                [234, 'OC', 'Вануату', -16.00, 167.00, 'Pacific/Efate', 'VU', Yii::t('app', 'Vanuatu'), 'Republic of Vanuatu', 'VUT', '548', 'yes', '678', '.vu', null, 'VUV', 0],
                [228, 'EU', 'Ватикан', 41.90, 12.45, 'Europe/Vatican', 'VA', Yii::t('app', 'Vatican City'), 'State of the Vatican City', 'VAT', '336', 'no', '39', '.va', 10, 'EUR', 0],
                [230, 'SA', 'Венесуэла', 8.00, -66.00, 'America/Caracas', 'VE', Yii::t('app', 'Venezuela'), 'Bolivarian Republic of Venezuela', 'VEN', '862', 'yes', '58', '.ve', null, 'VEF', 0],
                [233, 'AS', 'Вьетнам', 16.17, 107.83, 'Asia/Ho_Chi_Minh', 'VN', Yii::t('app', 'Vietnam'), 'Socialist Republic of Vietnam', 'VNM', '704', 'yes', '84', '.vn', null, 'VND', 0],
                //[244, 'VG', Yii::t('app', 'Virgin Islands, British'), 'British Virgin Islands', 'VGB', '092', 'no', '1-284', '.vg', 10, 'USD', 0],
                [232, 'NA', 'Виргинские Острова США', 18.35, -64.98, 'America/St_Thomas', 'VI', Yii::t('app', 'Virgin Islands, US'), 'Virgin Islands of the United States', 'VIR', '850', 'no', '1-340', '.vi', 10, 'USD', 0],
                [235, 'OC', 'Уоллис и Футуна', -13.30, -176.20, 'Pacific/Wallis', 'WF', Yii::t('app', 'Wallis and Futuna'), 'Wallis and Futuna', 'WLF', '876', 'no', '681', '.wf', null, 'XPF', 0],
                //[247, 'EH', Yii::t('app', 'Western Sahara'), 'Western Sahara', 'ESH', '732', 'no', '212', '.eh', null, 'MAD', 0],
                //[248, 'YE', Yii::t('app', 'Yemen'), 'Republic of Yemen', 'YEM', '887', 'yes', '967', '.ye', 9, null, 0],
                [241, 'AF', 'Замбия', -14.33, 28.50, 'Africa/Lusaka', 'ZM', Yii::t('app', 'Zambia'), 'Republic of Zambia', 'ZMB', '894', 'yes', '260', '.zm', null, 'ZMK', 0],
                [243, 'AF', 'Зимбабве', -19.00, 29.75, 'Africa/Harare', 'ZW', Yii::t('app', 'Zimbabwe'), 'Republic of Zimbabwe', 'ZWE', '716', 'yes', '263', '.zw', null, 'USD', 0]
            ]);
    }

    public function down()
    {
        $this->dropForeignKey('fk_country_region', 'geo_region');
        $this->dropForeignKey('fk_region_city', 'geo_city');

        $this->dropTable('geo_city');
        $this->dropTable('geo_region');
        $this->dropTable('geo_country');
    }
}
